print("### Fichero original ###")
flectura = open("prueba.txt", "r")
texto = flectura.read()
flectura.close()
print(texto)
print("### Insertando linea... ###\n")
fescritura = open("prueba.txt", "a")
fescritura.write("info@timesofsoftware.com\n")
fescritura.close()
print("### Fichero modificado ###")
flectura = open("prueba.txt", "r")
texto = flectura.read()
flectura.close()
print(texto)
